// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCRPLOTTER_H
#define UI_SCRPLOTTER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrPlotter
extern void ui_scrPlotter_screen_init(void);
extern void ui_scrPlotter_screen_destroy(void);
extern lv_obj_t *ui_scrPlotter;
extern lv_obj_t *ui_scrPlotter_contTopBar;
extern lv_obj_t *ui_scrPlotter_contDate;
extern lv_obj_t *ui_scrPlotter_chartView;
extern lv_obj_t *ui_scrPlotter_chartView_Xaxis;
extern lv_obj_t *ui_scrPlotter_chartView_Yaxis1;
extern lv_obj_t *ui_scrPlotter_chartView_Yaxis2;
extern lv_obj_t *ui_scrPlotter_contPeak;
extern lv_obj_t *ui_scrPlotter_lblPeak;
extern lv_obj_t *ui_scrPlotter_conPeakV;
extern lv_obj_t *ui_scrPlotter_lblPeakV;
extern lv_obj_t *ui_scrPlotter_contRms;
extern lv_obj_t *ui_scrPlotter_lblRms;
extern lv_obj_t *ui_scrPlotter_conRmsV;
extern lv_obj_t *ui_scrPlotter_lblRmsV;
extern lv_obj_t *ui_scrPlotter_contFreq;
extern lv_obj_t *ui_scrPlotter_lblFreq;
extern lv_obj_t *ui_scrPlotter_conFreqV;
extern lv_obj_t *ui_scrPlotter_lblFreqV;
extern lv_obj_t *ui_scrPlotter_contTime;
extern lv_obj_t *ui_scrPlotter_lblTime;
extern lv_obj_t *ui_scrPlotter_contTimeV;
extern lv_obj_t *ui_scrPlotter_lblTimeV;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

