// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_BOOT_H
#define UI_BOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_boot
extern void ui_boot_screen_init(void);
extern void ui_boot_screen_destroy(void);
extern lv_obj_t *ui_boot;
extern lv_obj_t *ui_boot_lbl_boot;
extern lv_obj_t *ui_boot_spin_loading;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

