// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#include "../ui.h"

lv_obj_t *ui_boot = NULL;lv_obj_t *ui_boot_lbl_boot = NULL;lv_obj_t *ui_boot_spin_loading = NULL;
// event funtions

// build funtions

void ui_boot_screen_init(void)
{
ui_boot = lv_obj_create(NULL);
lv_obj_remove_flag( ui_boot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_boot_lbl_boot = lv_label_create(ui_boot);
lv_obj_set_width( ui_boot_lbl_boot, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_boot_lbl_boot, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_boot_lbl_boot, 0 );
lv_obj_set_y( ui_boot_lbl_boot, -40 );
lv_obj_set_align( ui_boot_lbl_boot, LV_ALIGN_CENTER );
lv_label_set_text(ui_boot_lbl_boot,"Analizador Trifasico");
lv_obj_set_style_text_font(ui_boot_lbl_boot, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_boot_spin_loading = lv_spinner_create(ui_boot);
//lv_spinner_set_anim_params(ui_boot_spin_loading, 1000, 90);
lv_obj_set_width( ui_boot_spin_loading, 80);
lv_obj_set_height( ui_boot_spin_loading, 80);
lv_obj_set_x( ui_boot_spin_loading, 0 );
lv_obj_set_y( ui_boot_spin_loading, 50 );
lv_obj_set_align( ui_boot_spin_loading, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_boot_spin_loading, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_boot_spin_loading, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_boot_spin_loading, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_boot_spin_loading, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);

}

void ui_boot_screen_destroy(void)
{
   if (ui_boot) lv_obj_del(ui_boot);

// NULL screen variables
ui_boot= NULL;
ui_boot_lbl_boot= NULL;
ui_boot_spin_loading= NULL;

}
