// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_PLOTTER_H
#define UI_PLOTTER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_plotter
extern void ui_plotter_screen_init(void);
extern void ui_plotter_screen_destroy(void);
extern lv_obj_t *ui_plotter;
extern lv_obj_t *ui_plotter_view;
extern lv_obj_t *ui_plotter_view_Xaxis;
extern lv_obj_t *ui_plotter_view_Yaxis1;
extern lv_obj_t *ui_plotter_view_Yaxis2;
extern lv_obj_t *ui_plotter_view_controller;
extern lv_obj_t *ui_plotter_btn_vrms;
extern lv_obj_t *ui_plotter_lbl_rms;
extern lv_obj_t *ui_plotter_btn_freq;
extern lv_obj_t *ui_plotter_lbl_freq;
extern lv_obj_t *ui_plotter_btn_back;
// CUSTOM VARIABLES
extern lv_obj_t *ui_plotter;
extern lv_obj_t *ui_view;
extern lv_obj_t *ui_plotter_Panel_view_controller;
extern lv_obj_t *ui_lbl_rms;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

