// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#include "../ui.h"

lv_obj_t *ui_lbl_rms;
lv_obj_t *ui_plotter_Panel_view_controller;
lv_obj_t *ui_view;
lv_obj_t *ui_plotter;
lv_obj_t *ui_plotter = NULL;lv_obj_t *ui_plotter_view = NULL;lv_obj_t *ui_plotter_view_Xaxis = NULL;lv_obj_t *ui_plotter_view_Yaxis1 = NULL;lv_obj_t *ui_plotter_view_Yaxis2 = NULL;lv_obj_t *ui_plotter_view_controller = NULL;lv_obj_t *ui_plotter_btn_vrms = NULL;lv_obj_t *ui_plotter_lbl_rms = NULL;lv_obj_t *ui_plotter_btn_freq = NULL;lv_obj_t *ui_plotter_lbl_freq = NULL;lv_obj_t *ui_plotter_btn_back = NULL;
// event funtions

// build funtions

void ui_plotter_screen_init(void)
{
ui_plotter = lv_obj_create(NULL);
lv_obj_remove_flag( ui_plotter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_plotter_view = lv_chart_create(ui_plotter);
lv_obj_set_width( ui_plotter_view, 400);
lv_obj_set_height( ui_plotter_view, 280);
lv_obj_set_x( ui_plotter_view, 20 );
lv_obj_set_y( ui_plotter_view, 0 );
lv_obj_set_align( ui_plotter_view, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_plotter_view, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_plotter_view, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_plotter_view, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_plotter_view, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_plotter_view, LV_CHART_TYPE_LINE);
lv_chart_set_axis_range( ui_plotter_view, LV_CHART_AXIS_PRIMARY_Y, -250, 250);
lv_chart_set_axis_range( ui_plotter_view, LV_CHART_AXIS_SECONDARY_Y, 0, 0);

ui_plotter_view_Xaxis = lv_scale_create( ui_plotter_view );
lv_scale_set_mode( ui_plotter_view_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_plotter_view_Xaxis, lv_pct(100), 50 );
lv_obj_set_align( ui_plotter_view_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_plotter_view_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_plotter_view,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_plotter_view,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_plotter_view_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_plotter_view_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_plotter_view_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_plotter_view_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_plotter_view_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_plotter_view_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_plotter_view_Xaxis, (5>0 ? 5-1 : 0) * 5 + 1 );
lv_scale_set_major_tick_every( ui_plotter_view_Xaxis, 5 >= 1 ? 5 : 1 );
lv_scale_set_label_show( ui_plotter_view_Xaxis, false );
ui_plotter_view_Yaxis1 = lv_scale_create( ui_plotter_view );
lv_scale_set_mode( ui_plotter_view_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_plotter_view_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_plotter_view_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_plotter_view_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_plotter_view,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_plotter_view,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_plotter_view_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_plotter_view_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_plotter_view_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_plotter_view_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_plotter_view_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_range( ui_plotter_view_Yaxis1,  -250, 250 );
lv_scale_set_total_tick_count( ui_plotter_view_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_plotter_view_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_plotter_view_Yaxis2 = lv_scale_create( ui_plotter_view );
lv_scale_set_mode( ui_plotter_view_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_align( ui_plotter_view_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_style_line_width( ui_plotter_view_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_plotter_view_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_plotter_view_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_plotter_view_Yaxis2, 0, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_plotter_view_Yaxis2, 0, LV_PART_INDICATOR ); //major tick length
lv_scale_set_range( ui_plotter_view_Yaxis2,  0, 0 );
lv_scale_set_total_tick_count( ui_plotter_view_Yaxis2, (0 > 0 ? 0-1 : 0) * 0 + 1 );
lv_scale_set_major_tick_every( ui_plotter_view_Yaxis2, 0 >= 1 ? 0 : 1 );
lv_scale_set_label_show( ui_plotter_view_Yaxis2, false );

//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_plotter_view, LV_MAX3(50, 50, 0), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_plotter_view, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_plotter_view_controller = lv_obj_create(ui_plotter);
lv_obj_set_width( ui_plotter_view_controller, 80);
lv_obj_set_height( ui_plotter_view_controller, 320);
lv_obj_set_align( ui_plotter_view_controller, LV_ALIGN_RIGHT_MID );
lv_obj_remove_flag( ui_plotter_view_controller, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_plotter_view_controller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_plotter_view_controller, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_plotter_view_controller, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_plotter_view_controller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_plotter_view_controller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_plotter_view_controller, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_plotter_btn_vrms = lv_button_create(ui_plotter_view_controller);
lv_obj_set_width( ui_plotter_btn_vrms, 80);
lv_obj_set_height( ui_plotter_btn_vrms, 50);
lv_obj_set_align( ui_plotter_btn_vrms, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_plotter_btn_vrms, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_plotter_btn_vrms, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_plotter_btn_vrms, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_plotter_btn_vrms, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_plotter_btn_vrms, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor(ui_plotter_btn_vrms, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_plotter_btn_vrms, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_plotter_lbl_rms = lv_label_create(ui_plotter_btn_vrms);
lv_obj_set_width( ui_plotter_lbl_rms, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_plotter_lbl_rms, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_plotter_lbl_rms, LV_ALIGN_CENTER );
lv_label_set_text(ui_plotter_lbl_rms,"V(t)");

ui_plotter_btn_freq = lv_button_create(ui_plotter_view_controller);
lv_obj_set_width( ui_plotter_btn_freq, 80);
lv_obj_set_height( ui_plotter_btn_freq, 50);
lv_obj_set_x( ui_plotter_btn_freq, 0 );
lv_obj_set_y( ui_plotter_btn_freq, 50 );
lv_obj_set_align( ui_plotter_btn_freq, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_plotter_btn_freq, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_plotter_btn_freq, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_plotter_btn_freq, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_plotter_btn_freq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_plotter_btn_freq, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor(ui_plotter_btn_freq, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_plotter_btn_freq, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_plotter_lbl_freq = lv_label_create(ui_plotter_btn_freq);
lv_obj_set_width( ui_plotter_lbl_freq, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_plotter_lbl_freq, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_plotter_lbl_freq, LV_ALIGN_CENTER );
lv_label_set_text(ui_plotter_lbl_freq,"Hz");

ui_plotter_btn_back = lv_button_create(ui_plotter_view_controller);
lv_obj_set_width( ui_plotter_btn_back, 80);
lv_obj_set_height( ui_plotter_btn_back, 50);
lv_obj_set_align( ui_plotter_btn_back, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_plotter_btn_back, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_plotter_btn_back, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_plotter_btn_back, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_plotter_btn_back, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_plotter_btn_back, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_plotter_btn_back, &ui_img_icons_icon_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_plotter_btn_back, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_plotter_btn_back, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_plotter = ui_plotter;
ui_view = ui_plotter_view;
ui_plotter_Panel_view_controller = ui_plotter_view_controller;
ui_lbl_rms = ui_plotter_lbl_rms;

}

void ui_plotter_screen_destroy(void)
{
   if (ui_plotter) lv_obj_del(ui_plotter);

// NULL screen variables
ui_plotter= NULL;
ui_plotter= NULL;
ui_view= NULL;
ui_plotter_view= NULL;
ui_plotter_Panel_view_controller= NULL;
ui_plotter_view_controller= NULL;
ui_plotter_btn_vrms= NULL;
ui_lbl_rms= NULL;
ui_plotter_lbl_rms= NULL;
ui_plotter_btn_freq= NULL;
ui_plotter_lbl_freq= NULL;
ui_plotter_btn_back= NULL;

}
