// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#include "../ui.h"

lv_obj_t *ui_scrBoot = NULL;lv_obj_t *ui_scrBoot_lblWelcome = NULL;lv_obj_t *ui_scrBoot_spinWelcome = NULL;
// event funtions

// build funtions

void ui_scrBoot_screen_init(void)
{
ui_scrBoot = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrBoot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrBoot_lblWelcome = lv_label_create(ui_scrBoot);
lv_obj_set_width( ui_scrBoot_lblWelcome, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrBoot_lblWelcome, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrBoot_lblWelcome, 0 );
lv_obj_set_y( ui_scrBoot_lblWelcome, -40 );
lv_obj_set_align( ui_scrBoot_lblWelcome, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrBoot_lblWelcome,"Analizador Trifasico");
lv_obj_set_style_text_font(ui_scrBoot_lblWelcome, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrBoot_spinWelcome = lv_spinner_create(ui_scrBoot);
//lv_spinner_set_anim_params(ui_scrBoot_spinWelcome, 1000, 90);
lv_obj_set_width( ui_scrBoot_spinWelcome, 80);
lv_obj_set_height( ui_scrBoot_spinWelcome, 80);
lv_obj_set_x( ui_scrBoot_spinWelcome, 0 );
lv_obj_set_y( ui_scrBoot_spinWelcome, 50 );
lv_obj_set_align( ui_scrBoot_spinWelcome, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_scrBoot_spinWelcome, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_scrBoot_spinWelcome, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_scrBoot_spinWelcome, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_scrBoot_spinWelcome, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);

}

void ui_scrBoot_screen_destroy(void)
{
   if (ui_scrBoot) lv_obj_del(ui_scrBoot);

// NULL screen variables
ui_scrBoot= NULL;
ui_scrBoot_lblWelcome= NULL;
ui_scrBoot_spinWelcome= NULL;

}
