// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCRBOOT_H
#define UI_SCRBOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrBoot
extern void ui_scrBoot_screen_init(void);
extern void ui_scrBoot_screen_destroy(void);
extern lv_obj_t *ui_scrBoot;
extern lv_obj_t *ui_scrBoot_lblWelcome;
extern lv_obj_t *ui_scrBoot_spinWelcome;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

