// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#include "../ui.h"

lv_obj_t *ui_scrPlotter = NULL;lv_obj_t *ui_scrPlotter_chartView = NULL;lv_obj_t *ui_scrPlotter_chartView_Xaxis = NULL;lv_obj_t *ui_scrPlotter_chartView_Yaxis1 = NULL;lv_obj_t *ui_scrPlotter_chartView_Yaxis2 = NULL;lv_obj_t *ui_scrPlotter_pnlView = NULL;lv_obj_t *ui_scrPlotter_btnVrms = NULL;lv_obj_t *ui_scrPlotter_lblVrms = NULL;lv_obj_t *ui_scrPlotter_btnFreq = NULL;lv_obj_t *ui_scrPlotter_lblFreq = NULL;lv_obj_t *ui_scrPlotter_btnBack = NULL;
// event funtions

// build funtions

void ui_scrPlotter_screen_init(void)
{
ui_scrPlotter = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrPlotter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrPlotter_chartView = lv_chart_create(ui_scrPlotter);
lv_obj_set_width( ui_scrPlotter_chartView, 400);
lv_obj_set_height( ui_scrPlotter_chartView, 280);
lv_obj_set_x( ui_scrPlotter_chartView, 20 );
lv_obj_set_y( ui_scrPlotter_chartView, 0 );
lv_obj_set_align( ui_scrPlotter_chartView, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_scrPlotter_chartView, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_scrPlotter_chartView, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_scrPlotter_chartView, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_scrPlotter_chartView, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_scrPlotter_chartView, LV_CHART_TYPE_LINE);
lv_chart_set_axis_range( ui_scrPlotter_chartView, LV_CHART_AXIS_PRIMARY_Y, -250, 250);
lv_chart_set_axis_range( ui_scrPlotter_chartView, LV_CHART_AXIS_SECONDARY_Y, 0, 0);

ui_scrPlotter_chartView_Xaxis = lv_scale_create( ui_scrPlotter_chartView );
lv_scale_set_mode( ui_scrPlotter_chartView_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_scrPlotter_chartView_Xaxis, lv_pct(100), 50 );
lv_obj_set_align( ui_scrPlotter_chartView_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_scrPlotter_chartView_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_scrPlotter_chartView,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_scrPlotter_chartView,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_scrPlotter_chartView_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_scrPlotter_chartView_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_scrPlotter_chartView_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_scrPlotter_chartView_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_scrPlotter_chartView_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_scrPlotter_chartView_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_scrPlotter_chartView_Xaxis, (5>0 ? 5-1 : 0) * 5 + 1 );
lv_scale_set_major_tick_every( ui_scrPlotter_chartView_Xaxis, 5 >= 1 ? 5 : 1 );
lv_scale_set_label_show( ui_scrPlotter_chartView_Xaxis, false );
ui_scrPlotter_chartView_Yaxis1 = lv_scale_create( ui_scrPlotter_chartView );
lv_scale_set_mode( ui_scrPlotter_chartView_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_scrPlotter_chartView_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_scrPlotter_chartView_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_scrPlotter_chartView_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_scrPlotter_chartView,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_scrPlotter_chartView,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_scrPlotter_chartView_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_scrPlotter_chartView_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_scrPlotter_chartView_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_scrPlotter_chartView_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_scrPlotter_chartView_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_range( ui_scrPlotter_chartView_Yaxis1,  -250, 250 );
lv_scale_set_total_tick_count( ui_scrPlotter_chartView_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_scrPlotter_chartView_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_scrPlotter_chartView_Yaxis2 = lv_scale_create( ui_scrPlotter_chartView );
lv_scale_set_mode( ui_scrPlotter_chartView_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_align( ui_scrPlotter_chartView_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_style_line_width( ui_scrPlotter_chartView_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_scrPlotter_chartView_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_scrPlotter_chartView_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_scrPlotter_chartView_Yaxis2, 0, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_scrPlotter_chartView_Yaxis2, 0, LV_PART_INDICATOR ); //major tick length
lv_scale_set_range( ui_scrPlotter_chartView_Yaxis2,  0, 0 );
lv_scale_set_total_tick_count( ui_scrPlotter_chartView_Yaxis2, (0 > 0 ? 0-1 : 0) * 0 + 1 );
lv_scale_set_major_tick_every( ui_scrPlotter_chartView_Yaxis2, 0 >= 1 ? 0 : 1 );
lv_scale_set_label_show( ui_scrPlotter_chartView_Yaxis2, false );

//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_scrPlotter_chartView, LV_MAX3(50, 50, 0), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_scrPlotter_chartView, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_scrPlotter_pnlView = lv_obj_create(ui_scrPlotter);
lv_obj_set_width( ui_scrPlotter_pnlView, 80);
lv_obj_set_height( ui_scrPlotter_pnlView, 320);
lv_obj_set_align( ui_scrPlotter_pnlView, LV_ALIGN_RIGHT_MID );
lv_obj_remove_flag( ui_scrPlotter_pnlView, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrPlotter_pnlView, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrPlotter_pnlView, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrPlotter_pnlView, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_scrPlotter_pnlView, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_scrPlotter_pnlView, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_scrPlotter_pnlView, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrPlotter_btnVrms = lv_button_create(ui_scrPlotter_pnlView);
lv_obj_set_width( ui_scrPlotter_btnVrms, 80);
lv_obj_set_height( ui_scrPlotter_btnVrms, 50);
lv_obj_set_align( ui_scrPlotter_btnVrms, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_scrPlotter_btnVrms, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrPlotter_btnVrms, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrPlotter_btnVrms, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrPlotter_btnVrms, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrPlotter_btnVrms, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor(ui_scrPlotter_btnVrms, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_scrPlotter_btnVrms, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrPlotter_lblVrms = lv_label_create(ui_scrPlotter_btnVrms);
lv_obj_set_width( ui_scrPlotter_lblVrms, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrPlotter_lblVrms, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrPlotter_lblVrms, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrPlotter_lblVrms,"V(t)");

ui_scrPlotter_btnFreq = lv_button_create(ui_scrPlotter_pnlView);
lv_obj_set_width( ui_scrPlotter_btnFreq, 80);
lv_obj_set_height( ui_scrPlotter_btnFreq, 50);
lv_obj_set_x( ui_scrPlotter_btnFreq, 0 );
lv_obj_set_y( ui_scrPlotter_btnFreq, 50 );
lv_obj_set_align( ui_scrPlotter_btnFreq, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_scrPlotter_btnFreq, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrPlotter_btnFreq, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrPlotter_btnFreq, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrPlotter_btnFreq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrPlotter_btnFreq, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor(ui_scrPlotter_btnFreq, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_scrPlotter_btnFreq, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrPlotter_lblFreq = lv_label_create(ui_scrPlotter_btnFreq);
lv_obj_set_width( ui_scrPlotter_lblFreq, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrPlotter_lblFreq, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrPlotter_lblFreq, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrPlotter_lblFreq,"Hz");

ui_scrPlotter_btnBack = lv_button_create(ui_scrPlotter_pnlView);
lv_obj_set_width( ui_scrPlotter_btnBack, 80);
lv_obj_set_height( ui_scrPlotter_btnBack, 50);
lv_obj_set_align( ui_scrPlotter_btnBack, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_scrPlotter_btnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrPlotter_btnBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrPlotter_btnBack, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrPlotter_btnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrPlotter_btnBack, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_scrPlotter_btnBack, &ui_img_icons_icon_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_recolor(ui_scrPlotter_btnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_scrPlotter_btnBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_scrPlotter_screen_destroy(void)
{
   if (ui_scrPlotter) lv_obj_del(ui_scrPlotter);

// NULL screen variables
ui_scrPlotter= NULL;
ui_scrPlotter_chartView= NULL;
ui_scrPlotter_pnlView= NULL;
ui_scrPlotter_btnVrms= NULL;
ui_scrPlotter_lblVrms= NULL;
ui_scrPlotter_btnFreq= NULL;
ui_scrPlotter_lblFreq= NULL;
ui_scrPlotter_btnBack= NULL;

}
