// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCRPLOTTER_H
#define UI_SCRPLOTTER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrPlotter
extern void ui_scrPlotter_screen_init(void);
extern void ui_scrPlotter_screen_destroy(void);
extern lv_obj_t *ui_scrPlotter;
extern lv_obj_t *ui_scrPlotter_chartView;
extern lv_obj_t *ui_scrPlotter_chartView_Xaxis;
extern lv_obj_t *ui_scrPlotter_chartView_Yaxis1;
extern lv_obj_t *ui_scrPlotter_chartView_Yaxis2;
extern lv_obj_t *ui_scrPlotter_pnlView;
extern lv_obj_t *ui_scrPlotter_btnVrms;
extern lv_obj_t *ui_scrPlotter_lblVrms;
extern lv_obj_t *ui_scrPlotter_btnFreq;
extern lv_obj_t *ui_scrPlotter_lblFreq;
extern lv_obj_t *ui_scrPlotter_btnBack;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

